### ISSUE TITLE
Error with mermaid-open-browser

### ISSUE THREAD

**Issue by gjm** [abrochard/mermaid-mode#1]
When I try to open in a browser (`C-c C-o`) i get:
```
mermaid-open-browser: Symbol’s function definition is void: browse-url-default-browser
```
Is there something I have to configure?

I'm using emacs 26.1 on Ubuntu 19.04.

Thanks in advance!

**Comment by abrochard** [comment]
Thank you for your interest!
That is very weird. I am also on emacs 26.1 and I see `browse-url-default-browser` defined in `browse-url.el` which is part of the regular codebase?
What happens if you do a `C-h f browse-url-default-browser`? do you see the function defined?

**Comment by gjm** [comment]
@abrochard I don't have that function defined...

**Comment by abrochard** [comment]
So weird. That would be an interesting thing to ask on a forum or something.

As a workaround, I propose you define the function yourself?
https://github.com/emacs-mirror/emacs/blob/d0e2a341dd9a9a365fd311748df024ecb25b70ec/lisp/net/browse-url.el#L924
You could stick that guy into your config?

**Comment by gjm** [comment]
How about using `browse-url-xdg-open` instead of `browse-url-default-browser`? Doesn't that work?

**Comment by gjm** [comment]
Closed by mistake... sorry...

**Comment by gjm** [comment]
Fixed it!

Was using `use-package` to pull `mermaid-mode`. Had to `(require 'browse-url)` in package initialization. Seems to be working fine now.

Thanks!

**Comment by abrochard** [comment]
Awesome! Thank you! I wonder if I should add that require in the package....
