### ISSUE TITLE
How to use it in org mode

### ISSUE THREAD

**Issue by fountainer** [abrochard/mermaid-mode#10]
The variable `mermaid-mmdc-location`  is set as `"~/node_modules/.bin/mmdc"`. Pressing `C-c C-c` in the code block generates the error `error: option `-i, --input <input>' argument missing`. There is also a [ob-mermaid](https://github.com/arnm/ob-mermaid). I can use `ob-mermaid` when `mermaid-mode` is not installed. However, when `mermaid-mode` is installed, pressing `C-c C-c` in org mode generates the above error.

**Comment by abrochard** [comment]
Hi @fountainer , thank you for bringing this up. I just pushed a fix for it. Should be in Melpa soon.
