### ISSUE TITLE
Difference between mermaid-mode versus ob-mermaid?

### ISSUE THREAD

**Issue by HurriedPatience** [abrochard/mermaid-mode#12]
Hi Abrochard,

So nice of you to make this.  I'm looking forward to using mermaid on emacs.  But which do I choose?  Your mermaid-mode or [op-mermaid]([url](https://github.com/arnm/ob-mermaid/graphs/code-frequency))?

I'm asking you because it seems you uploaded this in [2019 ]([url](https://github.com/abrochard/mermaid-mode/graphs/code-frequency))whereas the other was started in [2018 ](https://github.com/arnm/ob-mermaid/graphs/code-frequency)on github.  You've updated your code more recently Mar 2020 versus Aug 2019. 

So what was your motivation to write different code?  What do you find missing in ob-mermaid?  Does yours contain everything from ob-mermaid? What are the strengths and weaknesses of each?  

Thankfully

**Comment by abrochard** [comment]
Hi @HurriedPatience ,
`ob-mermaid` is an extension for org-babel (which is are typically prefixed with `ob-`), which means its goal is to export org source blocks into mermaid diagrams.
`mermaid-mode` is a major mode for editing and working with mermaid markup language and it provides syntax highlighting and auto-indentation.
You can absolutely use both and that's what I do. I use the major mode to edit mermaid syntax in org source blocks, and then export to diagrams.
Best,
