### ISSUE TITLE
Add mermaid-compile-region and mermaid-open-region-in-browser

### ISSUE THREAD

**Issue by gjm** [abrochard/mermaid-mode#2]
Would be great if we could use regions for compiling and editing online, especially the latter.

**Comment by abrochard** [comment]
That's a pretty neat idea. I just pushed some code for that. `mermaid-open-browser` will run on the whole buffer or the active region if defined. Compiling is a little bit more tedious because mmdc requires a full file to run. I could save the region to a temp file somewhere but it's not great.

**Comment by gjm** [comment]
Seems to be working fine! Thanks!

**Comment by abrochard** [comment]
Sweet. I'll close the issue for now. If you really need regions for compiling feel free to let me know.
