### ISSUE TITLE
can mermaid-mode support chinese?

### ISSUE THREAD

**Issue by haoisli9** [abrochard/mermaid-mode#22]
I tried chinese in mermaid liveeditor, it seems ok.
but when I use chinese in emacs mermaid-mode, and compile it, it cause syntax error.

how can i use chinese in mermaid-mode? or how to construct mermaid cli command to support chinese?

I am in win10, emacs 29.0.50, mermaid file encoding with GBK or UTF-8 cause same thing.

thanks.

**Comment by abrochard** [comment]
Hi @haoisli9,
Thank you for reporting this. 
I am not very familiar with charset issues: the problem could come from Emacs itself, the mermaid CLI, or anything in between.
I think a good first step in debugging would be to install the mermaid CLI and try to compile a diagram with Chinese characters without using Emacs.
According to [this function](https://github.com/abrochard/mermaid-mode/blob/master/mermaid-mode.el#L172), the command should be `mmdc -i [input file] -o [output file]`.
If that command works and you're able to compile a mermaid diagram, then the problem is elsewhere.

**Comment by haoisli9** [comment]
Hi，So glad to receive from you.
I had tried mermaid-mode in emacs, and it can compile a diagram. but all the chinese in unreadable.

but mermaid CLI can be used in other program such as VS code, chinese is also OK.
So I think maybe i should speacial a charset or encoding method in mmdc, but i can not find how to do it.

Does mmdc have any flags to special input  charset?

Thanks.



***@***.***
 
From: Adrien Brochard
Date: 2022-07-24 01:03
To: abrochard/mermaid-mode
CC: haoisli9; Mention
Subject: Re: [abrochard/mermaid-mode] can mermaid-mode support chinese? (Issue #22)
Hi @haoisli9,
Thank you for reporting this.
I am not very familiar with charset issues: the problem could come from Emacs itself, the mermaid CLI, or anything in between.
I think a good first step in debugging would be to install the mermaid CLI and try to compile a diagram with Chinese characters without using Emacs.
According to this function, the command should be mmdc -i [input file] -o [output file].
If that command works and you're able to compile a mermaid diagram, then the problem is elsewhere.

**Comment by abrochard** [comment]
> Does mmdc have any flags to special input charset? 

That's a good question. I don't know at this point. I do encourage you to try the steps I describe above and play with `mmdc` directly.

**Comment by haoisli9** [comment]
Hi,

    I tried mmdc in command line, it can compile the diagram well when the input file encoding with UTF-8, but cause unreadable string when the file encoding is chinese-gbk.
    so I think the problem is mmdc assum that the input file in utf-8. 
    But windows default file encoding is gbk.  and VS code use mmdc with default file encoding, it can compile gbk file or string well. I guess mmdc has an input flag to speacial the encoding. or VS code convert string encoding when calling mmdc?

    Thanks.



***@***.***
 
From: Adrien Brochard
Date: 2022-07-28 13:11
To: abrochard/mermaid-mode
CC: haoisli9; Mention
Subject: Re: [abrochard/mermaid-mode] can mermaid-mode support chinese? (Issue #22)
Does mmdc have any flags to special input charset?
That's a good question. I don't know at this point. I do encourage you to try the steps I describe above and play with mmdc directly.
