### ISSUE TITLE
Consider adding file extensions to auto-mode-alist

### ISSUE THREAD

**Issue by danlamanna** [abrochard/mermaid-mode#29]
Something like:
```elisp
(add-to-list 'auto-mode-alist '("\\.mmd$" . mermaid-mode)))
```

See also https://github.com/mermaid-js/mermaid/issues/147.

I picked `mmd` because github seems to support that.

**Comment by abrochard** [comment]
Good suggestion! Thank you

**Comment by kurnevsky** [comment]
This change broke emacs: `Invalid regexp: "Trailing backslash"`

**Comment by rudi** [comment]
Discussion and workaround in #30
