### ISSUE TITLE
auto-mode-alist regex error

### ISSUE THREAD

**Issue by ShuguangSun** [abrochard/mermaid-mode#30]
`(add-to-list 'auto-mode-alist '("\\.mmd\\" . mermaid-mode))` should be `(add-to-list 'auto-mode-alist '("\\.mmd\\'" . mermaid-mode))`.

`\\'` is used to end the string.

**Comment by skat-kurt** [comment]
This issue results in emacs not being able to auto-load any mode, failing with `File mode specification error: (invalid-regexp Trailing backslash)`.

**Comment by rudi** [comment]
Worked around it by putting the following form into `.emacs/init.el` after loading mermaid mode:

`(setq auto-mode-alist (delete '("\\.mmd\\" . mermaid-mode) auto-mode-alist))`

**Comment by abrochard** [comment]
Thank you for reporting! I typod my last commit and forgot a trailing `'`. I just pushed a fix which worked for me locally.

**Comment by rudi** [comment]
Many thanks! I confirm it's working.
