### ISSUE TITLE
Indentation appears after cursor on new line

### ISSUE THREAD

**Issue by bricka** [abrochard/mermaid-mode#31]
Thanks for the package! I personally use Evil mode, but when I press Enter to go to the next line, the indentation appears after my cursor, so my cursor is not indented.

https://user-images.githubusercontent.com/318395/214833967-f31c23b4-8ea1-48c2-a669-a61f892118ac.mov

**Comment by bricka** [comment]
I had a quick look, and it actually even affects non-Evil users, whenever the new line should be indented further than the previous line. Just put up an MR to resolve it.

**Comment by abrochard** [comment]
Thank you so much for the issue and PR! I approved and merged!
