### ISSUE TITLE
Does mermaid-mode supports auto-suggestion similar to the mermaid.live editor?

### ISSUE THREAD

**Issue by sudhirkhanger** [abrochard/mermaid-mode#42]
Does mermaid-mode supports auto-suggestion similar to the mermaid.live editor?

![image](https://github.com/abrochard/mermaid-mode/assets/841656/54faea9b-055b-4d07-9352-35c717df1169)

**Comment by abrochard** [comment]
hi @sudhirkhanger , 
it currently does not. that would be a really cool addition
