### ISSUE TITLE
Specify mermaid.cli flags

### ISSUE THREAD

**Issue by Trisk3lion** [abrochard/mermaid-mode#7]
Hello, thanks for a great package!

Do you think we could add a way to specify cli flags?
I run this in WSL (Windows subsystem for linux) and i have to be able to specify the "-p" flag for puppeteer-config.json, otherwise mermaid won't run.

**Comment by abrochard** [comment]
Thank you very much!

I am not familiar with the `-p` flag. Would you be pointing to a static puppeteer-config.json file (like you can can set it once at Emacs startup and not think about it), or do you need something more dynamic?

If it's the former, I can create a configuration variable for you to set extra arguments to pass to the cli.

**Comment by Trisk3lion** [comment]
I can only speak for my use case, and for that it would be perfectly fine to just point at a static config file. 
I just use it to disable the sandbox mode for puppeteer.

**Comment by abrochard** [comment]
I just pushed https://github.com/abrochard/mermaid-mode/commit/a5b16bc4308e2a520711c2ef8a964e269115cbf7 that should do it. Let me know if it works for you
